/**
 * Writes docs/EVIDENCE.md from what the CHAIN says, not from any script's
 * memory: every check is re-read with get_check and verify_check, plus the
 * per-flag summary and the contract's books. Seed and lifecycle logs are
 * linked for the transaction hashes.
 *
 *   node collect.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { connect } from "./harness.mjs";

const dep = JSON.parse(readFileSync(new URL("../deployments.json", import.meta.url))).deployments.studiodev;
const plain = (x) => JSON.parse(JSON.stringify(x, (k, v) => (typeof v === "bigint" ? v.toString() : v instanceof Map ? Object.fromEntries(v) : v)));
const c = connect({ address: dep.TOSGuard.address, role: "trigger" });
const d = connect({ address: dep.TOSGuardDemo.address, role: "trigger" });

const recent = plain(await c.view("get_recent_checks", [50]));
const rows = [];
const details = [];
for (const item of [...recent.items].reverse()) {
  const ck = plain(await c.view("get_check", [item.check_id]));
  const v = plain(await c.view("verify_check", [item.check_id]));
  rows.push(`| ${ck.check_id} | ${ck.url} | ${ck.flag_type} | ${ck.status} | **${ck.outcome || "-"}** | ${ck.severity_bucket} | ${ck.clarity_bucket} | ${ck.scope_bucket} | ${ck.evidence_present} | ${ck.page_length_bucket} | ${ck.case || "-"} | ${ck.findings?.keyword_strength ?? "-"} | ${ck.findings?.model_called ?? "-"} | ${v.judged ? (v.verified ? "✔ " + v.checks.length + "/" + v.checks.length : "✘") : "-"} |`);
  details.push(`### #${ck.check_id} — ${ck.url} · ${ck.flag_type}\n\n` +
    `- findings key: \`${ck.findings_key || "-"}\`\n` +
    `- content hash: \`${ck.content_hash || "-"}\` (excerpt of ${ck.excerpt ? ck.excerpt.split("\n").length : 0} clauses, ${ck.findings?.matched_total ?? 0} matched on the page)\n` +
    `- allowed by the bracket: \`${ck.findings?.allowed || "-"}\`, ranges \`${ck.findings?.ranges || "-"}\`\n` +
    (ck.quote ? `- quote: “${ck.quote}”\n` : "") +
    `- reason: ${ck.reason}\n` +
    `- judge attempts: ${ck.judge_attempts}\n`);
}
const flags = plain(await c.view("get_vocabulary", [])).flags.map((f) => f.key);
const statRows = [];
for (const f of flags) {
  const s = plain(await c.view("get_flag_stats", [f]));
  statRows.push(`| ${f} | ${s.by_outcome.RED_FLAG} | ${s.by_outcome.CLEAN} | ${s.by_outcome.INCONCLUSIVE} | ${s.urls_flagged} / ${s.urls_judged} |`);
}
const stats = plain(await c.view("get_stats", []));
const dstats = plain(await d.view("get_stats", []));
const read = (f) => readFileSync(new URL("../docs/" + f, import.meta.url), "utf8");
const seedLog1 = read("seed-run1.log");
const seedLog2 = read("seed-run2.log");
const compare = read("seed-compare.md");
const lifeLog = read("lifecycle-run.log");

const md = `# EVIDENCE — read back from Studio Dev

Generated by \`test/collect.mjs\` from the chain at ${new Date().toISOString()}.
Every row below was re-read with \`get_check\` and re-derived with
\`verify_check\`, which rebuilds every stored field (case, allowed set, ranges,
outcome, severity, clarity, scope, evidence_present, counts, facts hash,
keyword strength, content hash, findings key, quote, reason) from the stored
excerpt alone.

- Canonical \`TOSGuard\`: \`${dep.TOSGuard.address}\` (cooldown ${dep.TOSGuard.cooldown_s}s, stall ${dep.TOSGuard.stall_ttl_s}s), deploy tx \`${dep.TOSGuard.deploy_tx}\`
- Demo \`TOSGuardDemo\` (same bytes): \`${dep.TOSGuardDemo.address}\` (cooldown ${dep.TOSGuardDemo.cooldown_s}s, stall ${dep.TOSGuardDemo.stall_ttl_s}s)
- Source sha256 \`${dep.TOSGuard.source_sha256}\` (${dep.TOSGuard.source_bytes} bytes) — \`tools/audit.py\` check 32 compares it with \`contracts/TOSGuard.py\`
- Explorer: ${dep.explorer}

## Run 1 vs run 2 (\`test/compare_runs.mjs\`)

The nine seed checks were filed and judged twice, as separate checks on the
same deployment. Every exact field is compared, re-read from the chain.

${compare.trim()}

## Every check on the canonical instance

| # | URL | flag | status | outcome | sev | clr | scp | evidence | len | case | strength | model | verify |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
${rows.join("\n")}

## Per-flag summary (\`get_flag_stats\`)

| flag | RED_FLAG | CLEAN | INCONCLUSIVE | URLs flagged / judged |
|---|---|---|---|---|
${statRows.join("\n")}

## Books

- canonical: ${stats.checks} checks, ${stats.judgments} judgments in ${stats.judge_attempts} attempts (${stats.unsettled_attempts} unsettled), ${stats.refusals} refusals, balance ${stats.balance_wei} wei, ledger balanced: ${stats.ledger_balanced}
- demo: ${dstats.checks} checks, ${dstats.stalled} stalled, ${dstats.refusals} refusals, balance ${dstats.balance_wei} wei, ledger balanced: ${dstats.ledger_balanced}

## Detail

${details.join("\n")}
## Seed run 1 (\`test/seed.mjs --run=1\`)

\`\`\`
${seedLog1.trim()}
\`\`\`

## Seed run 2 (\`test/seed.mjs --run=2\`)

\`\`\`
${seedLog2.trim()}
\`\`\`

## Lifecycle run (\`test/lifecycle.mjs\`)

\`\`\`
${lifeLog.trim()}
\`\`\`
`;
writeFileSync(new URL("../docs/EVIDENCE.md", import.meta.url), md);
console.log("wrote docs/EVIDENCE.md");
