#!/usr/bin/env python3
"""What the scanner makes of each probed render (docs/probe/), using the
contract's OWN pure functions on the exact bytes a validator saw:

    python3 tools/probe_report.py > docs/probe-report.md

For every seed candidate: did the page load, how many characters, the keyword
strength (distinct indicator families), which indicators, the gate case and
allowed outcomes, and the first 500 characters of the relevant clauses.
"""
import ast
import sys
import types
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = (ROOT / "contracts" / "TOSGuard.py").read_text(encoding="utf8")
stub = types.ModuleType("genlayer")
stub.gl = types.SimpleNamespace()
names = ["Address", "u8", "u16", "u32", "u64", "u128", "u256", "i32", "i64", "bigint"]
for n in names:
    setattr(stub, n, str if n == "Address" else int)
stub.__all__ = names
sys.modules.setdefault("genlayer", stub)
tree = ast.parse(SRC)
tree.body = tree.body[:next(i for i, n in enumerate(tree.body) if isinstance(n, ast.ClassDef))]
P = types.ModuleType("pure")
exec(compile(tree, "TOSGuard.py", "exec"), P.__dict__)

PROBE = ROOT / "docs" / "probe"
CANDIDATES = [
    ("https://x.com/en/tos", "x_com_en_tos.txt", ["CONTENT_OWNERSHIP", "MANDATORY_ARBITRATION", "DATA_SALE"]),
    ("https://duckduckgo.com/terms", "duckduckgo_com_terms.txt", ["DATA_SALE", "MANDATORY_ARBITRATION"]),
    ("https://discord.com/terms", "discord_com_terms.txt", ["CONTENT_OWNERSHIP", "ACCOUNT_TERMINATION"]),
    ("https://zoom.us/en/terms", "zoom_us_en_terms.txt", ["DATA_SALE"]),
    ("https://github.com/site/terms", "github_com_site_terms.txt", ["CONTENT_OWNERSHIP"]),
    ("https://example.com/", "example_com_.txt", ["DATA_SALE"]),
]

out = ["# Probe report — the v1.2.0 scanner on real renders", "",
       "Generated by `tools/probe_report.py` from the bytes in `docs/probe/`, which a",
       "Studio Dev validator rendered through `contracts/_render_probe.py`.", "",
       "| URL · flag | loaded | chars | matching clauses | strength | indicators | case | allowed |",
       "|---|---|---|---|---|---|---|---|"]
detail = []
for url, fname, flags in CANDIDATES:
    path = PROBE / fname
    text = path.read_text(encoding="utf8") if path.exists() else ""
    loaded = bool(text)
    for f in flags:
        ev = P._read_page(text, loaded, f)
        br = P._bracket(f, ev)
        an = br["analysis"]
        out.append("| %s · %s | %s | %s | %d | %d | %s | %s | %s |" % (
            url, f, "yes" if loaded else "**no**", format(len(text), ","), ev["matched_total"],
            br["strength"], ", ".join(an["indicators"]) or "—", br["case"], " / ".join(br["allowed"])))
        rel = "\n".join(sorted(an["signal"], key=lambda s: (-len(P._families(s, P._flag(f))), s))[:6])
        if an["denied"]:
            rel += ("\n" if rel else "") + "[denial] " + "\n[denial] ".join(an["denied"][:3])
        detail.append("### %s · %s\n\n```\n%s\n```\n" % (url, f, (rel or "(no matching clause)")[:500]))
print("\n".join(out) + "\n\n## First 500 characters of the relevant clauses\n\n" + "\n".join(detail))
